### ISSUE TITLE
I got no view of overlay

### ISSUE THREAD

**Issue by ezequias** [hyrious/obs-input-overlay-zxc-arrows#1] opened 2021-07-31 11:05 UTC
Hi

I was trying to load this overlay to my obs 26.1.1 64bits and it doesn't work.

Could you give me some directions to make it work?

I also would like to load only the arrow keys.

Thanks a lot
ezequias

**Comment by hyrious** [comment] 2021-07-31 11:26
It looks like input-overlay has changed the config syntax in [v4.8](https://github.com/univrsal/input-overlay/releases/tag/v4.8). You could try to change the config file according to the info.

It also looks like they have v5.0…… I'll make the 5.0 config file soon.

**Comment by hyrious** [comment] 2021-07-31 12:02
> I also would like to load only the arrow keys.

Then you may have to create your own texture and config.

Reference to the `VC_*` values: https://github.com/kwhat/libuiohook/blob/1.2/include/uiohook.h#L134

**Comment by ezequias** [comment] 2021-08-02 14:04
> It looks like input-overlay has changed the config syntax in [v4.8](https://github.com/univrsal/input-overlay/releases/tag/v4.8). You could try to change the config file according to the info.
> 
> It also looks like they have v5.0…… I'll make the 5.0 config file soon.

I failed to make it work here. 🙁

**Comment by hyrious** [comment] 2021-09-17 07:46
The config works for me on my obs & input overlay & windows 10 (both at the latest stable version). So I'll close this issue.

Feel free to re-open it if you could find a way to let me reproduce it.
But I'll suggest you to post this issue to [input overlay](https://github.com/univrsal/input-overlay) or the [obs studio](https://github.com/obsproject/obs-studio) because they have more experience on dealing with such things.

**Closed as completed by hyrious** 2021-09-17 07:46 UTC
